services:
  - type: web
    name: lms-backend
    env: node
    plan: free
    buildCommand: "npm install && pip install pdfplumber"
    startCommand: "npm run start"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false
